alias npm='docker run -it -e "HOME=/tmp" -u $(id -u) -e NODE_ENV=${NODE_ENV} -e BUILD_NUMBER=${BUILD_NUMBER} --rm -v "$(pwd)":/usr/src/app -w /usr/src/app node:5 npm'
alias node='docker run -it -e "HOME=/tmp" -u $(id -u) -e NODE_ENV=${NODE_ENV} -e BUILD_NUMBER=${BUILD_NUMBER} --rm -v "$(pwd)":/usr/src/app -w /usr/src/app node:5 node'
alias npm_dev='docker run -it -e "HOME=/tmp" -u $(id -u) -e NODE_ENV=${NODE_ENV} -e BUILD_NUMBER=${BUILD_NUMBER} --rm -p 3000:3000 -v "$(pwd)":/usr/src/app -w /usr/src/app node:5 npm'
alias docker_clean='docker rm $(docker ps -a -q --filter status=exited); docker volume rm $(docker volume ls -qf dangling=true)'
alias dterm='docker run --privileged -v /var/run/docker.sock:/run/docker.sock -ti --rm -e TERM=$TERM tomastomecek/sen'
alias vundle_clone='git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim'
alias gitgid='git config user.email "anovmari@gmail.com" && git config user.name "Anton Marianov"'
alias gitvid='git config user.email "amarianov@viewster.com" && git config user.name "Anton Marianov"'
alias lnsda='sudo ln -s /host/mnt/sda1 /mnt/'
alias cdp='cd /mnt/sda1/projects'
alias mysql='docker run -i --rm mariadb mysql'
alias mysqldump='docker run -i --rm mariadb mysqldump'
alias dip='docker inspect -f '\''{{.Name}} - {{.NetworkSettings.IPAddress }}'\'' $(docker ps -aq)'
alias di='docker inspect --format '\''{{ .NetworkSettings.IPAddress }}'\'' '
alias dbroot='docker run -it --link dev_db_1:mysql --rm mysql/mysql-server sh -c '\''exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'\'
alias fixrights='sudo find -type f -exec chmod a+rw {} \; && sudo find -type d -exec chmod a+rwx {} \;'
alias www='docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy'
alias samba='docker run -d -p 139:139 -p 445:445 -v /mnt/sda1/:/mnt/sda1 dperson/samba -s "sda1;/mnt/sda1/;yes;no"'
